package ProyectoFinal.model.enums;

public enum Especialidad {
    MEDICINA_GENERAL,
    MEDICINA_INTERNA,
    ANOTOMIA_PATOLOGICA,
    CIRUGIA,
    PEDIATRIA,
    OBSTETRICIA_Y_GINECOLOGIA,
    DERMATOLOGIA,
    CARDIOLOGIA,
    NEUROLOGIA,
    ONCOLOGIA,
    PSIQUIATRIA

}
